package at.need2eat.need2eat;

import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.*;

/**
 * This class contains the interface of the EditActivity, which allows the user to edit
 * information of a product manually.
 * @author Sebastian Feistl
 */
public class EditActivity extends AppCompatActivity {

  /** The full name of the particular product. */
  String productname;

  /** The barcode saved as digits of the particular product. */
  String gtin;

  /** The expiration date of the particular product. */
  String date;

  /**
   * Autogenerated function that initializes the layout of this class.
   * @param savedInstanceState TODO: Look up what the heck that is
   */
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    setContentView(R.layout.activity_edit);
    setData("Tutti Frutti", "0184977832175", "10.12.2017");
    initializeLayout();
  }

  /**
   * Function to initialize all important elements and applies onClickListeners to the buttons.
   * Furthermore it sets the current existing information (name of the product, barcode,
   * expiration date).
   */
  private void initializeLayout() {

    final EditText PRODUCTNAME_EDIT = (EditText)findViewById(R.id.productNameEdit);
    final EditText GTIN_EDIT = (EditText)findViewById(R.id.gtinTextEdit);
    final EditText DATE_EDIT = (EditText)findViewById(R.id.dateTextEdit);
    final LinearLayout BACK_BUTTON = (LinearLayout)findViewById(R.id.backButton);
    final LinearLayout ACCEPT_BUTTON = (LinearLayout)findViewById(R.id.acceptButton);

    BACK_BUTTON.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {

      }
    });

    ACCEPT_BUTTON.setOnClickListener(new View.OnClickListener() {
      @Override
      public void onClick(View v) {
        productname = PRODUCTNAME_EDIT.getText().toString();
        gtin = GTIN_EDIT.getText().toString();
        date = DATE_EDIT.getText().toString();
      }
    });

    PRODUCTNAME_EDIT.setText(productname);
    GTIN_EDIT.setText(gtin);
    DATE_EDIT.setText(date);
  }

  /**
   * Function to set or update the information of the product.
   * @param productname is the full name of the current product.
   * @param gtin is the barcode of the product, saved as digits.
   * @param date is the expiration date of the product.
   */
  private void setData(String productname, String gtin, String date) {
    this.productname = productname;
    this.gtin = gtin;
    this.date = date;
  }

}
